apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: 271153858532.dkr.ecr.ap-southeast-1.amazonaws.com/admin21-flower-delivery:v1 
          ports:
            - containerPort: 8080
